version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          key: v2-app-{{ .Branch }}
          key: v2-app-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v2-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - .git
      - run: npm run stop-only
      - run: npm run types
      - run: npm run test:ci:record
