# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

# for non-orb configuration see old commit
# https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml

# to use CircleCI orbs need to use version >= 2.1
version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.11.0

executors:
  mac:
    macos:
      xcode: "10.1.0"
    environment:
      # install Cypress in Linux-like cache folder
      # that the orb saves after install
      # this could be done by the Orb IF Cypress handled "~/..." paths better during verify
      # https://github.com/cypress-io/circleci-orb/issues/98
      # https://github.com/cypress-io/cypress/issues/5386
      CYPRESS_CACHE_FOLDER: /Users/distiller/.cache/Cypress

jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release

workflows:
  mac-build:
    jobs:
      - cypress/install:
          name: 'Mac install'
          executor: mac
          # and builds the app using this command
          build: 'npm run build'
          post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
            - run: npx cypress cache path
            - run: npx cypress cache list

      - cypress/run:
          name: Mac test
          executor: mac
          requires:
            - Mac install
          record: true
          parallel: true
          parallelism: 2
          start: 'npm run start:ci'
          group: 'Mac build'

  linux-build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          name: 'Linux install'
          # and builds the app using this command
          build: 'npm run build'
          post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
            - run: npx cypress cache path
            - run: npx cypress cache list

      # runs on 3 machines, load balances tests
      # and records on Cypress Dashboard
      - cypress/run:
          # name this job because we are running "cypress/run" several times
          # with different parameters
          name: '3 machines'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          record: true # record results on Cypress dashboard
          parallel: true # load balance all tests
          parallelism: 3 # across 3 machines
          group: '3x-electron on CircleCI' # name this group
          start: 'npm run start:ci' # start server before running tests

      # run on 2 machines using Chrome browser
      - cypress/run:
          name: '2 machines using Chrome'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome69
          # use browser "chrome" for running tests
          browser: chrome
          record: true
          parallel: true
          parallelism: 2
          group: '2x-chrome on CircleCI'
          start: 'npm run start:ci'

      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - 3 machines
