env:
  TERM: "xterm"
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a


steps:
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     redefine config set stable_branch=master
        # redefine verify --cypress

  - label: "run cypress in dry run"
    command: | 
      # pip install -U redefine --index-url https://redefine.dev/pip/
      pip install ${BUILDKITE_BUILD_CHECKOUT_PATH}/redefine-0.14.17.post6-py3-none-manylinux1_x86_64.whl
      redefine config set environment=staging
      redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      redefine config set dry_run=true
      redefine start --discover --cypress
      npm install cypress@10.7
      # use date to check how long it takes to run the dry run
      date && npx cypress run 1> specs.txt && date
      mkdir -p redefine
      cp specs.txt redefine
      cat redefine/specs.txt
    artifact_paths:
      - "redefine/specs.txt"
  - wait

  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - artifacts#v1.9.0:
          download: "redefine/specs.txt"
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app/redefine"
          propagate-environment: true
