env:
  TERM: "xterm"

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  - name: ":docker: docker tests"
    parallelism: 3
    plugins:
      - docker-compose#v3.7.0:
          run: app
