env:
  TERM: "xterm"

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  - label: ":cypress: Cypress"
    parallelism: 3
    command: |
      echo "--- Installing Redefine"
      pip install redefine --index-url https://redefine.dev/pip/

      redefine config set fallback_strategy=FALLBACK_STRATEGY_RUN_NOTHING
      redefine config set stable_branch=master

      redefine verify --pytest

      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "+++ Run Cypress tests"
      docker build --network=host --pull --rm -f "Dockerfile" -t img "cypress_model" |
          --build-arg BUILDKITE_BUILD_CHECKOUT_PATH |
          --build-arg BUILDKITE_BUILD_ID = $BUILDKITE_BUILD_ID |
          --build-arg BUILDKITE_PIPELINE_NAME = $BUILDKITE_PIPELINE_NAME |
          --build-arg BUILDKITE_LABEL = $BUILDKITE_LABEL |
          --build-arg BUILDKITE_BRANCH = $BUILDKITE_BRANCH |
          --build-arg BUILDKITE_COMMIT = $BUILDKITE_COMMIT |
          --build-arg BUILDKITE_PULL_REQUEST = $BUILDKITE_PULL_REQUEST |
          --build-arg BUILDKITE_PULL_REQUEST_BASE_BRANCH = $BUILDKITE_PULL_REQUEST_BASE_BRANCH |
          --build-arg BUILDKITE_PARALLEL_JOB_COUNT = $BUILDKITE_PARALLEL_JOB_COUNT
