env:
  TERM: "xterm"

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  - label: ":cypress: Cypress"
    parallelism: 3
    command: |
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "+++ Run Cypress tests"
      docker build --network=host --pull --rm -f "Dockerfile" -t img "."
