env:
  TERM: "xterm"
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
  REDEFINE_AUTH: 65d9546e7d0e6aa7870ed0e0dce71ffdb5121d86

steps:
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     redefine config set stable_branch=master
        # redefine verify --cypress 
  - label: "run cypress in dry run"
    command: | 
      mkdir -p /tmp/redefine
      mkdir -p redefine
      rm -f $BUILDKITE_BUILD_CHECKOUT_PATH/effective_config.yml
      npm install
      pip uninstall -y redefine
      pip install -U redefine --index-url https://redefine.dev/pip
      #pip install -U redefine --index-url https://redefine.dev/staging/pip
      #redefine config set environment=staging
      #redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      rm -f /tmp/redefine/redefine_specs.txt
      redefine start --verbose --cypress --prioritize --dry-run --output-path=/tmp/redefine/redefine_specs.txt
      export REDEFINE_DEBUG_MODE=True
      # use date to check how long it takes to run the dry run
      date && npx cypress run --env REDEFINE_DEBUG_MODE=True && date
      cat /tmp/redefine/redefine_specs.txt
      cp /tmp/redefine/redefine_specs.txt redefine/redefine_specs.txt

    artifact_paths:
      - redefine/redefine_specs.txt
  - wait



  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
    plugins:
      - artifacts#v1.9.0:
          download: redefine/redefine_specs.txt
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "redefine:/app/redefine"
          propagate-environment: true
