env:
  TERM: "xterm"
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a


steps:
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     redefine config set stable_branch=master
        # redefine verify --cypress
  - label: "run cypress in dry run"
    command: | 
      mkdir -p redefine
      rm -f $BUILDKITE_BUILD_CHECKOUT_PATH/effective_config.yml
      npm install
      pip uninstall -y redefine
      pip install -U redefine --index-url https://redefine.dev/staging/pip
      redefine config set environment=staging
      redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      rm -f ./redefine/redefine_specs.txt
      redefine start --verbose --cypress --prioritize --dry-run --output-path=./redefine/redefine_specs.txt
      export REDEFINE_DEBUG_MODE=True
      # use date to check how long it takes to run the dry run
      date && npx cypress run --env REDEFINE_DEBUG_MODE=True && date
      cat ./redefine/redefine_specs.txt
    artifact_paths:
      - ./redefine/redefine_specs.txt
  - wait

  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
    plugins:
      - artifacts#v1.9.0:
          download: redefine/*
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app/redefine"
          propagate-environment: true
