env:
  TERM: "xterm"

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  - label: ":cypress: Cypress"
    parallelism: 3
    command: |
      echo "--- Installing Redefine"
      pip install redefine --index-url https://redefine.dev/pip/

      redefine config set fallback_strategy=FALLBACK_STRATEGY_RUN_NOTHING
      redefine config set stable_branch=master

      redefine verify --pytest

      redefine
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "+++ Run Cypress tests"
      docker build --network=host --pull --rm -f "Dockerfile" -t img "."
