env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     scripts/verify_redefine.sh
  - label: "foo"
    command: | 
      pip3 install -U redefine --index-url https://redefine.dev/pip/
      redefine config set stable_branch=master
      redefine config set dry_run=true
      redefine start --verbose --discover --cypress
  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - docker-compose#v3.7.0:
          run: app
