env:
  TERM: "xterm"

steps:
  - label: ":cypress: Cypress"
    command: |
      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "--- Install NPM dependencies"
      npm install

      # if necessary, reinstall "correct" version of Cypress
      # a common situation if testing preview binary build
      # npx cypress install --force
      #
      echo "--- Install custom Cypress version"
      npm install "$CYPRESS_NPM_PACKAGE_NAME"

      echo "--- Cypress version"
      npx cypress version

      echo "+++ Run Cypress tests"
      npm run test:ci:record
