env:
  TERM: "xterm"

steps:
  - label: ":eyeglasses: Read Envs"
    command: |
      scripts/read_envs.sh
  - label: ":cypress: Cypress"
    parallelism: 3
    command: |
      echo "--- Installing Redefine"
      pip install redefine --index-url https://redefine.dev/pip/

      redefine config set fallback_strategy=FALLBACK_STRATEGY_RUN_NOTHING
      redefine config set stable_branch=master

      redefine verify --pytest

      echo "--- Node version"
      node --version

      echo "--- NPM version"
      npm --version

      echo "+++ Run Cypress tests"
      docker build --pull --rm -f "Dockerfile" -t cypressmodel "." \
          --build-arg BUILDKITE_BUILD_CHECKOUT_PATH="$BUILDKITE_BUILD_CHECKOUT_PATH" \
          --build-arg BUILDKITE_BUILD_ID="$BUILDKITE_BUILD_ID" \
          --build-arg BUILDKITE_PIPELINE_NAME="$BUILDKITE_PIPELINE_NAME" \
          --build-arg BUILDKITE_LABEL="$BUILDKITE_LABEL" \
          --build-arg BUILDKITE_BRANCH="$BUILDKITE_BRANCH" \
          --build-arg BUILDKITE_COMMIT="$BUILDKITE_COMMIT" 
