env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a


steps:
  # - label: ":eyeglasses: Read Envs"
  #   command: |
  #     scripts/read_envs.sh
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     scripts/verify_redefine.sh
  - label: "foo"
    command: | 
      # pip install -U redefine --index-url https://redefine.dev/pip/
      pip3 install ${BUILDKITE_BUILD_CHECKOUT_PATH}/redefine-0.14.16.post8-py3-none-manylinux1_x86_64.whl
      redefine config set environment=staging
      redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      redefine config set dry_run=true
      redefine start --verbose --discover --cypress
      npm install cypress
      npx cypress run  > 1.txt
      cat 1.txt
      
      

  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - docker-compose#v3.7.0:
          run: app
          propagate-environment: true
