name: Chrome Docker

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  # run Chrome inside a Docker container
  chrome:
    name: Chrome (Docker)
    runs-on: ubuntu-26.04
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:24.21.0
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Chrome
        uses: cypress-io/github-action@c541a95ea92d9239347a2355f2e895cd4b3f8060 # v7.4.6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
