name: Chrome Docker

on: [push, workflow_dispatch]

jobs:
  # run Chrome inside a Docker container
  chrome:
    runs-on: ubuntu-24.04
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:24.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Chrome
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
