name: Chrome Docker

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  # run Chrome inside a Docker container
  chrome:
    name: Chrome (Docker)
    runs-on: ubuntu-26.04
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:24.21.0
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Chrome
        uses: cypress-io/github-action@789d836053c5ca389c2905fc0c9f2909da778c46 # v7.4.5
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
