name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in all browsers and resolutions
        run: npm run cy:run --browser all --resolution all
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}

  cypress-tests-selected:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser:
          - chrome
          - edge
          - firefox
          - safari
        resolution:
          - 1536x864
          - 1920x1080
          - 1366x768
          - 1280x720

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in selected browser and resolution
        run: npm run cy:run --browser ${{ matrix.browser }} --resolution ${{ matrix.resolution }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}