name: Firefox

on: push

jobs:
  firefox:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: firefox
