name: 'Handle Comment Workflow'
on:
  issue_comment:
    types:
      - created
jobs:
  closed-issue-comment:
    if: github.repository_owner == 'cypress-io'
    uses: cypress-io/cypress/.github/workflows/triage_handle_new_comments.yml@develop
    secrets: inherit
