apiVersion: v1alpha
metadata:
  name: Feature XYZ
  tags:
  - e2e
  - release team
  - other tag
  build: Release $CI_COMMIT_SHORT_SHA
suites:
- name: saucy test
  match: .*.(spec|test).js$
files:
- cypress/
- cypress.json
image:
  base: saucelabs/stt-cypress-mocha-node
  version: v0.1.19
sauce:
  region: us-west-1
